const ADD_FINANCIAL_DATA = "ADD_FINANCIAL_DATA",
  FINANCIAL_DATA_LOADING = "FINANCIAL_DATA_LOADING",
  ADD_ERR_FINANCIAL_DATA = "ADD_ERR_FINANCIAL_DATA",
  SET_MODAL_FINANCIAL_DATA = "SET_MODAL_FINANCIAL_DATA",
  SET_FINANCIAL_DATA = "SET_FINANCIAL_DATA",
  SET_FINANCIAL_APPLICANTONE = "SET_FINANCIAL_APPLICANTONE",
  SET_FINANCIAL_APPLICANTTWO = "SET_FINANCIAL_APPLICANTTWO",
  REMOVETESTATE="REMOVETESTATE";

export {
  ADD_FINANCIAL_DATA,
  FINANCIAL_DATA_LOADING,
  ADD_ERR_FINANCIAL_DATA,
  SET_MODAL_FINANCIAL_DATA,
  SET_FINANCIAL_DATA,
  SET_FINANCIAL_APPLICANTTWO,
  SET_FINANCIAL_APPLICANTONE,
  REMOVETESTATE
};
