const ADD_MEETING="ADD_MEETING",
MEETING_LOADING="MEETING_LOADING",
ADD_ERR_MEETING="ADD_ERR_MEETING",
SET_MODAL_MEETIN="SET_MODAL_MEETIN",
SET_day="SET_day"


export {ADD_MEETING,MEETING_LOADING,ADD_ERR_MEETING,SET_MODAL_MEETIN,SET_day}